src/FileHelper.php
=> fix #1 add missing argument for recusrsive removeDirectory method call

README.md
=> Added general usage examples

src/FileHelper.php
=> Optimize path normilizing for isWindowShare

src/FileHelper.php
=> Optimize redundant `if` statement

.travis.yml
=> Add php7.4beta to travis config for extend tests

tests/FileHelperTest.php
=> Add several tests.

README.md, composer.json, psalm.xml
| New feature?  | ✔️/❌
| Fixed issues  |
=> Adopt Psalm

tests/FileHelperTest.php
=> Fixing unlink() under Windows

src/FileHelper.php, tests/FileHelperTest.php
=> Add FileHelper::lastModifiedTime().

.github/workflows/build.yml, .github/workflows/mutation.yml, .github/workflows/static.yml, README.md, composer.json
=> Update dev depedencies, pipelines and README.md.

composer.json, src/FileHelper.php, tests/FileHelperTest.php
=> Make argument $path in FileHelper::lastModifiedTime() to variadic

src/PathMatcher/CompositeMatcher.php, tests/PathMatcher/CompositeMatcherTest.php
=> Fix #43: Implement composite matcher

README.md, composer.json, src/PathMatcher/PathMatcher.php, src/PathMatcher/PathPattern.php, tests/FileHelperCopyDirectoryTest.php, tests/FileHelperFindDirectoriesTest.php, tests/FileHelperFindFilesTest.php, tests/PathMatcher/PathMatcherTest.php, tests/PathMatcher/PathPatternTest.php
| Breaks BC?    | ✔️
| Fixed issues  | https://github.com/yiisoft/strings/pull/67
=> Adjust to changes in yiisoft/strings

src/FileHelper.php
=> Improve phpdoc in FileHelper::findFiles() + minor improvements

CHANGELOG.md, src/PathMatcher/PathMatcher.php, tests/PathMatcher/PathMatcherTest.php
=> Directory separator was not normalized in patterns

CHANGELOG.md, src/FileHelper.php, src/PathMatcher/PathMatcher.php
=> PHP 8 improvements

CHANGELOG.md, README.md, src/FileHelper.php, tests/FileHelperTest.php
=> Add filter option for FileHelper::clearDirectory

CHANGELOG.md, src/FileHelper.php
| Fixed issues  | #47
This opiton was added in https://github.com/yiisoft/files/pull/68
=> Remove `filter` option from `FileHelper::removeDirectory()`

README.md
=> For issue #67: Add docs for FileHelper::copyFile()

README.md
=> PR for 49: add link to path matching info

.styleci.yml, tests/FileSystemTestCase.php, tests/PathMatcher/PathPatternTest.php
=> Update StyleCI config

CHANGELOG.md, src/FileHelper.php, tests/FileHelperRestoreErrorHandlerTest.php, tests/Support/StubErrorHandler.php
=> Restore error handler after throw exception

CHANGELOG.md, src/FileHelper.php
=> Suppress `filemtime()` warnings
